default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("POSTGRES_USER") { } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch("POSTGRES_PORT", "5432") %>
  password: password

development:
  <<: *default
  database: kiwanis_development
  host: <%= ENV.fetch("DATABASE_HOST") { } %>

test:
  <<: *default
  database: kiwanis_test
  host: <%= ENV.fetch("DATABASE_HOST") { } %>

production:
  <<: *default
  database: kiwanis_production
  username: kiwanis
  password: <%= ENV['KIWANIS_DATABASE_PASSWORD'] %>